# Generated by Django 4.1 on 2022-08-20 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=500)),
                ('access_token', models.CharField(max_length=1000)),
                ('public_id', models.CharField(max_length=1000)),
                ('profession', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('profile_photo', models.FileField(upload_to='')),
                ('profile_photo_path', models.CharField(max_length=500)),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Jouney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travelling_from', models.CharField(max_length=200)),
                ('travelling_to', models.CharField(max_length=200)),
                ('travelling_date', models.DateField()),
                ('status', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpool.person')),
            ],
        ),
    ]
