# Generated by Django 4.1 on 2022-08-20 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jouney',
            new_name='Journey',
        ),
    ]
