# Generated by Django 4.1 on 2022-08-20 19:16

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpool', '0002_rename_jouney_journey'),
    ]

    operations = [
        migrations.AddField(
            model_name='journey',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2022, 8, 20, 19, 16, 33, 877576)),
        ),
        migrations.AddField(
            model_name='journey',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2022, 8, 20, 19, 16, 33, 877589)),
        ),
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2022, 8, 20, 19, 16, 33, 876998)),
        ),
        migrations.AddField(
            model_name='person',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name=datetime.datetime(2022, 8, 20, 19, 16, 33, 877017)),
        ),
        migrations.CreateModel(
            name='Topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('details', models.CharField(max_length=1000)),
                ('photo_file', models.FileField(upload_to='')),
                ('photo_file_path', models.CharField(max_length=1000)),
                ('attach_file', models.FileField(upload_to='')),
                ('attach_file_path', models.CharField(max_length=1000)),
                ('status', models.IntegerField()),
                ('category', models.CharField(max_length=200)),
                ('topic_type', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpool.person')),
            ],
        ),
    ]
